name: digitalrepository-lib-unb-ca
services:
  digitalrepository-lib-unb-ca:
    container_name: digitalrepository-lib-unb-ca
    build:
      context: .
      target: development
    env_file:
      - env/hyrax.env
    depends_on:
      # - worker
      # - chrome
      - digitalrepository-fits-lib-unb-ca
      # - digitalrepository-memcached-lib-unb-ca
      - digitalrepository-postgres-lib-unb-ca
      - digitalrepository-redis-lib-unb-ca
      - digitalrepository-solr-lib-unb-ca
    ports:
      - 3080:3000
      - 9876:9876
      - 1048:1048
    volumes:
      - ./app:/rails/app
      - ./config:/rails/config
      - ./db:/rails/db
      - ./test:/rails/test
    networks:
      - digitalrepository.lib.unb.ca

  digitalrepository-postgres-lib-unb-ca:
    image: postgres:15-alpine
    container_name: digitalrepository-postgres-lib-unb-ca
    env_file:
      - env/postgres.env
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - digitalrepository.lib.unb.ca

  digitalrepository-redis-lib-unb-ca:
    image: redis:7-alpine
    container_name: digitalrepository-redis-lib-unb-ca
    restart: unless-stopped
    ports:
      - 6379
    networks:
      - digitalrepository.lib.unb.ca

  digitalrepository-solr-lib-unb-ca:
    image: solr:9
    container_name: digitalrepository-solr-lib-unb-ca
    env_file:
      - env/solr.env
    ports:
      - 8983:8983
    command:
      [
        "sh",
        "-c",
        "precreate-core digitalrepo-test /var/solr/data/digitalrepo-test/conf; solr-precreate digitalrepo /var/solr/data/digitalrepo/conf",
      ]
    volumes:
      - ./solr/conf:/var/solr/data/digitalrepo/conf
      - ./solr/conf:/var/solr/data/digitalrepo-test/conf
    ulimits:
      nofile:
        soft: 65536
        hard: 524288
    networks:
      - digitalrepository.lib.unb.ca

  # digitalrepository-memcached-lib-unb-ca:
  #   image: bitnami/memcached
  #   ports:
  #     - '11213:11211'
  #   networks:
  #     - digitalrepository.lib.unb.ca

  digitalrepository-fits-lib-unb-ca:
    image: ghcr.io/samvera/fitsservlet:1.6.0
    container_name: digitalrepository-fits-lib-unb-ca
    ports:
      - 8080:8080
    networks:
      - digitalrepository.lib.unb.ca

networks:
  digitalrepository.lib.unb.ca:
    name: digitalrepository.lib.unb.ca

volumes:
  db:
