name: digitalrepository-lib-unb-ca
services:
  digitalrepository-lib-unb-ca:
    container_name: digitalrepository-lib-unb-ca
    build:
      context: .
      target: development
    env_file:
      - env/hyrax.env
    depends_on:
      # - worker
      # - chrome
      - digitalrepository-fits-lib-unb-ca
      # - digitalrepository-memcached-lib-unb-ca
      - digitalrepository-postgres-lib-unb-ca
      - digitalrepository-redis-lib-unb-ca
      - digitalrepository-solr-lib-unb-ca
    ports:
      - 3080:3000
      - 9876:9876
      - 1048:1048
    volumes:
      - .:/rails
      # - rails-public:/app/samvera/hyrax-webapp/public
      # - rails-tmp:/app/samvera/hyrax-webapp/tmp
    networks:
      - digitalrepository.lib.unb.ca

  digitalrepository-postgres-lib-unb-ca:
    image: postgres:15-alpine
    container_name: digitalrepository-postgres-lib-unb-ca
    env_file:
      - env/postgres.env
    ports:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - digitalrepository.lib.unb.ca

  digitalrepository-redis-lib-unb-ca:
    image: redis:5-alpine
    container_name: digitalrepository-redis-lib-unb-ca
    restart: unless-stopped
    ports:
      - 6379
    networks:
      - digitalrepository.lib.unb.ca

  digitalrepository-solr-lib-unb-ca:
    image: solr:8.11
    ports:
      - 8983:8983
    command: ["sh", "-c", "precreate-core digitalrepo-test /opt/solr/server/configsets/hyraxconf; solr-precreate digitalrepo /opt/solr/server/configsets/hyraxconf"]
    volumes:
      # - solr_home:/var/solr/data:cached
      - ./solr/conf:/opt/solr/server/configsets/hyraxconf
    ulimits:
      nofile:
        soft: 65536
        hard: 524288
    networks:
      - digitalrepository.lib.unb.ca

  # digitalrepository-memcached-lib-unb-ca:
  #   image: bitnami/memcached
  #   ports:
  #     - '11213:11211'
  #   networks:
  #     - digitalrepository.lib.unb.ca

  digitalrepository-fits-lib-unb-ca:
    image: ghcr.io/samvera/fitsservlet:1.6.0
    ports:
      - 9080:8080
    networks:
      - digitalrepository.lib.unb.ca
  
networks:
  digitalrepository.lib.unb.ca:
    name: digitalrepository.lib.unb.ca

volumes:
  db:
