# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource Book`

attributes:
  creator:
    type: string
    multiple: true
    form:
      required: true
      primary: true
    index_keys:
      - "creator_sim"
      - "creator_tesim"
    predicate: http://purl.org/dc/elements/1.1/creator
    view:
      render_as: "faceted"
      html_dl: true
  subject:
    type: string
    multiple: true
    index_keys:
      - "subject_sim"
      - "subject_tesim"
    form:
      primary: true
    predicate: http://purl.org/dc/elements/1.1/subject
    view:
      render_as: "faceted"
      html_dl: true
  description:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "description_sim"
      - "description_tesim"
    predicate: http://purl.org/dc/elements/1.1/description
  publisher:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "publisher_sim"
      - "publisher_tesim"
    predicate: http://purl.org/dc/elements/1.1/publisher
    view:
      render_as: "faceted"
      html_dl: true
  contributor:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "contributor_tesim"
      - "contributor_sim"
    predicate: http://purl.org/dc/elements/1.1/contributor
    view:
      render_as: "faceted"
      html_dl: true
  date_created:
    type: date_time
    multiple: true
    form:
      primary: true
    index_keys:
      - "date_created_sim"
      - "date_created_tesim"
    predicate: http://purl.org/dc/terms/created
    view:
      render_as: "linked"
      search_field: 'date_created_tesim'
      html_dl: true
  resource_type:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "resource_type_sim"
      - "resource_type_tesim"
    predicate: http://purl.org/dc/terms/type
    view:
      render_as: "faceted"
      html_dl: true
  format:
    type: string
    multiple: true
    index_keys:
      - "format_sim"
      - "format_tesim"
    form:
      primary: true
    predicate: http://purl.org/dc/elements/1.1/format
    view:
      render_as: "faceted"
      html_dl: true
  identifier:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "identifier_sim"
      - "identifier_tesim"
    predicate: http://purl.org/dc/terms/identifier
    view:
      render_as: "linked"
      search_field: 'identifier_tesim'
      html_dl: true
  source:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "source_sim"
      - "source_tesim"
    predicate: http://purl.org/dc/terms/source
    view:
      html_dl: true
  language:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "language_sim"
      - "language_tesim"
    predicate: http://purl.org/dc/elements/1.1/language
    view:
      render_as: "faceted"
      html_dl: true
  # related resource, URI, https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#relation
  relation:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "relation_sim"
      - "relation_tesim"
    predicate: http://purl.org/dc/terms/relation
    view:
      render_as: "external_link"
      html_dl: true
  coverage:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "coverage_sim"
      - "coverage_tesim"
    predicate: http://purl.org/dc/terms/coverage
    view:
      render_as: "faceted"
      html_dl: true
  access_right:
    type: string
    multiple: true
    form:
      primary: true
    index_keys:
      - "access_right_sim"
      - "access_right_tesim"
    predicate: http://purl.org/dc/terms/accessRights
    view:
      html_dl: true
  
  
