# Local development and testing only.
# https://github.com/samvera/hyrax/wiki/Setting-up-test-app-for-workflow
development:
  admin:
    - j.doe@unb.ca

test:

production:
  # Add a production admin user:
  # https://github.com/samvera/hyrax/wiki/Making-Admin-Users-in-Hyrax
  admin: []
